#This file was autogenerated on 2025-04-27 21:59:33
import os
import subprocess
import pandas as pd
import re
import sys

def QSPICE_CCM_Boost_PFC_AMC(AC_freq, Cfp_I, Cfp_V, Cfz_I, Cfz_V, Cout, Cout_ESR, Dboost_fwd, Dboost_rdiff, eff, fsw, L, Pout, R_EMI, rdson, REC_fwd, REC_rdiff, Rf_I, Rf_V, Rsense, VAC_rms, Vout, export_traces = None):
    if export_traces is None:
         export_traces = [] 
    #### Create circuit file ####
    cir_file_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), "CCM_Boost_PFC_AMC.cir")
    results_file_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), "results.txt")
    csv_file_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), "CCM_Boost_PFC_AMC.csv")
    base_dir = os.path.dirname(os.path.realpath(__file__))
    f = open(cir_file_path, "w", newline="\n")

    #### Circuit Definition ####
    f.write("* Auto-Generated Netlist File" + "\n")
    f.write("D1 N01 N04 REC" + "\n")
    f.write("V1 N03 N02 SIN 0 {VAC_rms*sqrt(2)} {AC_freq}" + "\n")
    f.write("D2 N02 N04 REC" + "\n")
    f.write("D3 N05 N01 REC" + "\n")
    f.write("D4 N05 N02 REC" + "\n")
    f.write("L1 N14 N06 {L}" + "\n")
    f.write("D5 N06 OUT boostD" + "\n")
    f.write("D6 N04 OUT REC" + "\n")
    f.write("C1 OUT N12 {Cout} IC=0" + "\n")
    f.write("S1 N06 0 PWM 0 MODSW" + "\n")
    f.write("R2 N10 N08 1K" + "\n")
    f.write("R3 N08 N07 {Rf_I}" + "\n")
    f.write("C2 N07 N09 {Cfz_I}" + "\n")
    f.write("C3 N08 N09 {Cfp_I}" + "\n")
    f.write("V3 VCC 0 15" + "\n")
    f.write("V4 VEE 0 0" + "\n")
    f.write("¥3 VLOG 0 PWM ¥ N09 SAW VLOG ¥ ¥ ¥ ¥ ¥ ¥ ¥ ¥ ¥ HMITT TTOL={I_ttol_factor/fsw} VH=2m" + "\n")
    f.write("V7 VLOG 0 1" + "\n")
    f.write("C7 N04 N16 1µ" + "\n")
    f.write("D7 0 N06 ideal" + "\n")
    f.write("B2 0 N11 I=V(LINE_FWD)*V(Verr)" + "\n")
    f.write("R4 N12 0 {Cout_ESR}" + "\n")
    f.write("G1 0 LINE_FWD N04 N05 I_kVin" + "\n")
    f.write("R5 LINE_FWD 0 1" + "\n")
    f.write("G2 0 N13 OUT 0 {I_Vref/Vout}" + "\n")
    f.write("R8 N13 0 1" + "\n")
    f.write("R1 OUT 0 {Vout*Vout/(Pout/eff)}" + "\n")
    f.write("V2 N15 N01 0" + "\n")
    f.write("V8 SAW 0 PULSE {1/I_kMOD} 0 0 {(I_ttol_factor*10)/fsw} {(1-I_ttol_factor*10)/fsw} 0 {1/fsw}" + "\n")
    f.write("R10 N04 N14 {I_Res_L}" + "\n")
    f.write("R11 N16 N05 1m" + "\n")
    f.write("H1 N10 0 L1 {I_Ri}" + "\n")
    f.write("R6 N11 0 1" + "\n")
    f.write("R12 N13 N17 10K" + "\n")
    f.write("R13 N17 N18 {Rf_V}" + "\n")
    f.write("C6 N18 Verr {Cfz_V}" + "\n")
    f.write("C8 N17 Verr {Cfp_V}" + "\n")
    f.write("D8 Verr VCC ideal" + "\n")
    f.write("D9 0 Verr ideal" + "\n")
    f.write("D10 N09 VCC ideal" + "\n")
    f.write("D11 0 N09 ideal" + "\n")
    f.write("G3 0 N09 N11 N08 100K" + "\n")
    f.write("R14 N09 0 1" + "\n")
    f.write("C4 N09 0 100K/10Meg/2/pi" + "\n")
    f.write("G4 0 Verr N19 N17 100K" + "\n")
    f.write("R9 Verr 0 1" + "\n")
    f.write("C5 Verr 0 100K/10Meg/2/pi" + "\n")
    f.write("I1 0 N19 1µ" + "\n")
    f.write("R15 N19 0 {I_Vref/1e-6}" + "\n")
    f.write("C9 N19 0 20n IC=0" + "\n")
    f.write("V5 0 N20 0" + "\n")
    f.write("R7 N15 N03 R_EMI" + "\n")
    f.write("R16 N05 N20 {Rsense}" + "\n")

    #### Parameters ####
    f.write(".param eff=" + str(eff) + "\n")
    f.write(".param Pout=" + str(Pout) + "\n")
    f.write(".param Vout=" + str(Vout) + "\n")
    f.write(".param fsw=" + str(fsw) + "\n")
    f.write(".param Cout_ESR=" + str(Cout_ESR) + "\n")
    f.write(".param Cout=" + str(Cout) + "\n")
    f.write(".param REC_fwd=" + str(REC_fwd) + "\n")
    f.write(".param REC_rdiff=" + str(REC_rdiff) + "\n")
    f.write(".param rdson=" + str(rdson) + "\n")
    f.write(".param Dboost_fwd=" + str(Dboost_fwd) + "\n")
    f.write(".param Dboost_rdiff=" + str(Dboost_rdiff) + "\n")
    f.write(".param L=" + str(L) + "\n")
    f.write(".param VAC_rms=" + str(VAC_rms) + "\n")
    f.write(".param AC_freq=" + str(AC_freq) + "\n")
    f.write(".param Cfp_I=" + str(Cfp_I) + "\n")
    f.write(".param Rf_I=" + str(Rf_I) + "\n")
    f.write(".param Cfz_I=" + str(Cfz_I) + "\n")
    f.write(".param Cfp_V=" + str(Cfp_V) + "\n")
    f.write(".param Rf_V=" + str(Rf_V) + "\n")
    f.write(".param Cfz_V=" + str(Cfz_V) + "\n")
    f.write(".param R_EMI=" + str(R_EMI) + "\n")
    f.write(".param Rsense=" + str(Rsense) + "\n")
    f.write(".param I_kVin={1.5/(sqrt(2)*VAC_RMS)}" + "\n")
    f.write(".param I_kMOD=0.2" + "\n")
    f.write(".param TSTART={TSTOP-1/AC_freq}" + "\n")
    f.write(".param TSTOP={1}" + "\n")
    f.write(".param TSTEP={(1/fsw)/50}" + "\n")
    f.write(".param I_ttol_factor = 0.0001" + "\n")
    f.write(".param I_Res_L=0.1e-3" + "\n")
    f.write(".param I_Vref = 2.5" + "\n")
    f.write(".param I_IL_peak = sqrt(2) * Pout * (1 + (-sqrt(2) * VAC_RMS ** 3 + VAC_RMS ** 2 * Vout) / L / Pout / Vout / fsw / 2) / eff / VAC_RMS" + "\n")
    f.write(".param I_Ri = 1/I_IL_peak" + "\n")

    #### Models ####
    f.write(".model REC D(Vfwd={REC_fwd}, Ron={REC_rdiff}, Roff = 10Meg, Cjo=10p)" + "\n")
    f.write(".model ideal D(Vfwd=0,Ron=1m, Roff=10Meg)" + "\n")
    f.write(".model boostD D(Vfwd={Dboost_fwd},Ron={Dboost_rdiff}, Roff = 10Meg)" + "\n")
    f.write(".model MODSW SW(ron={rdson} roff=10Meg vt=0.5 vh=-0.05 )" + "\n")

    #### Libs ####
    f.write(".lib C:\\Users\\Stani\\QSPICE\\Diode.txt" + "\n")

    #### Spice Options ####
    f.write(".options trtol=1" + "\n")

    #### Measurement Definition ####
    f.write(".meas I_L_RMS rms I(L1)" + "\n") # results[0]
    f.write(".meas I_Dboost_RMS rms I(D5)" + "\n") # results[1]
    f.write(".meas I_L_PEAK max I(L1)" + "\n") # results[2]
    f.write(".meas I_FET_RMS rms I(S1)" + "\n") # results[3]
    f.write(".meas I_Dboost_AVG avg I(D5)" + "\n") # results[4]
    f.write(".meas I_Cout_RMS rms I(C1)" + "\n") # results[5]
    f.write(".meas I_REC_RMS rms I(D1)" + "\n") # results[6]
    f.write(".meas I_REC_AVG avg I(D1)" + "\n") # results[7]
    f.write(".meas V_Cout_MAX max V(out)" + "\n") # results[8]
    f.write(".meas I_IN_RMS rms I(V1)" + "\n") # results[9]
    f.write(".meas I_RSENSE_RMS rms I(V5)" + "\n") # results[10]

    #### SPICE Analysis ####
    f.write(".tran 0 {TSTOP} {TSTART} {TSTEP}" + "\n")

    f.write(".end")

    f.close()
    results = { 
        "I_L_RMS": 0,
        "I_Dboost_RMS": 0,
        "I_L_PEAK": 0,
        "I_FET_RMS": 0,
        "I_Dboost_AVG": 0,
        "I_Cout_RMS": 0,
        "I_REC_RMS": 0,
        "I_REC_AVG": 0,
        "V_Cout_MAX": 0,
        "I_IN_RMS": 0,
        "I_RSENSE_RMS": 0,
    }
    # Assume that QSPICE is installed in its default path for non-Admin user
    exe_qspice64 = os.path.expanduser(r"~\QSPICE\QSPICE64.exe")
    exe_qpost = os.path.expanduser(r"~\QSPICE\QPOST.exe")
    exe_qux = os.path.expanduser(r"~\QSPICE\QUX.exe")

    # run QSPICE Simulation
    try:
        run_qspice64 = subprocess.Popen([exe_qspice64, "CCM_Boost_PFC_AMC.cir"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, cwd = base_dir, bufsize=1, universal_newlines=True)
        for line in run_qspice64.stdout:
            print(line, end="")
            sys.stdout.flush()

        run_qspice64.wait()

        # Check exit code after process is done
        if run_qspice64.returncode == 0:
            print("QSPICE64 simulation completed successfully.")
            print('*************** END ***************')
        else:
            print(f"QSPICE64 simulation failed with exit code {run_qspice64.returncode}.")
            raise SystemExit("Terminating execution because simulation failed.")
    except subprocess.CalledProcessError as e:
        print('QSPICE64 exec output:')
        print(e.stderr)

    # Run postprocess measurement
    try:
        run_qpost = subprocess.run([exe_qpost, "CCM_Boost_PFC_AMC.cir", "-o", "results.txt"], capture_output=True, text=True, check=True, cwd = base_dir)
    except subprocess.CalledProcessError as e:
        print('QPOST exec output:')
        print(e.stderr)

    f = open(results_file_path, "r")
    results_lines = f.readlines()
    f.close()

    # Run postprocess waveforms extraction
    df = 0 
    if export_traces:
        run_qux = subprocess.run([exe_qux, "-Export", "CCM_Boost_PFC_AMC.qraw", export_traces, "all", "CSV"], cwd = base_dir)
        df = pd.read_csv(csv_file_path) 
        df.columns = df.columns.str.lower() 

        #Delete Exported Waveforms CSV File 
        subprocess.run(["del", "CCM_Boost_PFC_AMC.csv"], shell=True, cwd = base_dir) 

    # Delete Results
    subprocess.run(["del", "CCM_Boost_PFC_AMC.qraw"], shell=True, cwd = base_dir)

    # Delete Netlist
    subprocess.run(["del", "CCM_Boost_PFC_AMC.cir"], shell=True, cwd = base_dir)

    # Delete QPOST Results
    subprocess.run(["del", "results.txt"], shell=True, cwd = base_dir)
    for i, line in enumerate(results_lines):
        stripped_line = line.strip()
        match stripped_line:
            case ".meas i_l_rms rms i(l1):": 
                results['I_L_RMS'] = float(re.search(r'[-+]?\d*\.\d+|\d+', results_lines[i + 1])[0])

            case ".meas i_dboost_rms rms i(d5):": 
                results['I_Dboost_RMS'] = float(re.search(r'[-+]?\d*\.\d+|\d+', results_lines[i + 1])[0])

            case ".meas i_l_peak max i(l1):": 
                results['I_L_PEAK'] = float(re.search(r'[-+]?\d*\.\d+|\d+', results_lines[i + 1])[0])

            case ".meas i_fet_rms rms i(s1):": 
                results['I_FET_RMS'] = float(re.search(r'[-+]?\d*\.\d+|\d+', results_lines[i + 1])[0])

            case ".meas i_dboost_avg avg i(d5):": 
                results['I_Dboost_AVG'] = float(re.search(r'[-+]?\d*\.\d+|\d+', results_lines[i + 1])[0])

            case ".meas i_cout_rms rms i(c1):": 
                results['I_Cout_RMS'] = float(re.search(r'[-+]?\d*\.\d+|\d+', results_lines[i + 1])[0])

            case ".meas i_rec_rms rms i(d1):": 
                results['I_REC_RMS'] = float(re.search(r'[-+]?\d*\.\d+|\d+', results_lines[i + 1])[0])

            case ".meas i_rec_avg avg i(d1):": 
                results['I_REC_AVG'] = float(re.search(r'[-+]?\d*\.\d+|\d+', results_lines[i + 1])[0])

            case ".meas v_cout_max max v(out):": 
                results['V_Cout_MAX'] = float(re.search(r'[-+]?\d*\.\d+|\d+', results_lines[i + 1])[0])

            case ".meas i_in_rms rms i(v1):": 
                results['I_IN_RMS'] = float(re.search(r'[-+]?\d*\.\d+|\d+', results_lines[i + 1])[0])

            case ".meas i_rsense_rms rms i(v5):": 
                results['I_RSENSE_RMS'] = float(re.search(r'[-+]?\d*\.\d+|\d+', results_lines[i + 1])[0])

    return [df,results]